name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    services:
      localstack:
        container_name: localstack
        image: localstack/localstack:latest
        ports:
          - '${LOCALSTACK_PORT}:${LOCALSTACK_PORT}'
        environment:
          - SERVICES=sqs
          - AWS_DEFAULT_REGION=${AWS_SQS_REGION}
          - EDGE_PORT=${LOCALSTACK_PORT}
          - DEBUG=${LOCALSTACK_DEBUG- }
        volumes:
          - '${LOCALSTACK_TMPDIR:-/tmp/localstack}:/tmp/localstack'
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '${PWD}/scripts/sqs-local-setup.sh:/docker-entrypoint-initaws.d/sqs-local-setup.sh'

    steps:
      - name: echo
        run: echo Hello, world!
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: check lint
        run: npm run lint
      - name: npm test
        env:
          AWS_SQS_ENDPOINT: http://localhost:4566
        run: npm run test:e2e
